REFANG_PATTERNS = {
    "hxxps[://]": "https://",
    "hxxp[://]": "http://",
    "hxxps[:]//": "https://",
    "hxxp[:]//": "http://",
    "hxxps://": "https://",
    "hxxp://": "http://",
    "https[:]//": "https://",
    "http[:]//": "http://",
    "[.]": ".",
    "(.)": ".",
    "{.}": ".",
    "[dot]": ".",
    "(dot)": ".",
    " dot ": ".",
    "[:]": ":",
    "[@]": "@",
    "(at)": "@",
    "[at]": "@",
}
